package Vista;

import AppAccount.AccountManager;
import AppGameSetup.SessionManager;
import Model.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.ParseException;

/**
 *
 * @author GROUP 1 UNC
 */
public class ChangePasswordGUI extends javax.swing.JFrame {

    String username;

    /**
     * Creates new form ChangePasswordGUI
     */
    public ChangePasswordGUI(String username) {
        this.username = username;
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image1 = new javax.swing.JLabel();
        title1Label = new javax.swing.JLabel();
        oldPasswordLabel = new javax.swing.JLabel();
        newPasswordLabel = new javax.swing.JLabel();
        confirmNewPasswordLabel = new javax.swing.JLabel();
        actualPassword = new javax.swing.JPasswordField();
        newPassword = new javax.swing.JPasswordField();
        confirmNewPassword = new javax.swing.JPasswordField();
        change = new javax.swing.JButton();
        goBaCk = new javax.swing.JButton();
        aboutLabel = new javax.swing.JLabel();
        imageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        image1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Warriors.jpg"))); // NOI18N
        getContentPane().add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, 110));

        title1Label.setFont(new java.awt.Font("AR DESTINE", 0, 48)); // NOI18N
        title1Label.setForeground(new java.awt.Color(255, 0, 0));
        title1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1Label.setText("DSDRisk Game");
        getContentPane().add(title1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 78));

        oldPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        oldPasswordLabel.setText("Actual password");
        getContentPane().add(oldPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        newPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        newPasswordLabel.setText("New password");
        getContentPane().add(newPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        confirmNewPasswordLabel.setForeground(new java.awt.Color(0, 0, 0));
        confirmNewPasswordLabel.setText("Confirm new password");
        getContentPane().add(confirmNewPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        getContentPane().add(actualPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 143, -1));
        getContentPane().add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 143, -1));
        getContentPane().add(confirmNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 143, -1));

        change.setText("Change");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        getContentPane().add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        goBaCk.setText("Go Back");
        goBaCk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBaCkActionPerformed(evt);
            }
        });
        getContentPane().add(goBaCk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 90, -1));

        aboutLabel.setForeground(new java.awt.Color(0, 0, 204));
        aboutLabel.setText("About this game");
        getContentPane().add(aboutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        imageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background.jpg"))); // NOI18N
        getContentPane().add(imageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 480, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBaCkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBaCkActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_goBaCkActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        if (newPassword.getText().equals(confirmNewPassword.getText())) {
            if (newPassword.getText().length() >= 6 && newPassword.getText().length() <= 20) {
                try {
                    JSONArray array = AccountManager.changePassword(username, actualPassword.getText(), newPassword.getText());
                    boolean status = (boolean) (((JSONObject) (array.get(0))).get("status"));
                    String message = (String) (((JSONObject) (array.get(0))).get("message"));
                    if (status) {
                        JOptionPane.showMessageDialog(this, message, "Message", JOptionPane.INFORMATION_MESSAGE);
                        JOptionPane.showOptionDialog(null, message, "Message",
                                JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE,
                                null, new Object[]{"Accept"}, null);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showOptionDialog(null, message, "Message",
                                JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE,
                                null, new Object[]{"Accept"}, null);
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(LogInGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: The password must be between 6 and 20 characters");
            }
        } else {
            JOptionPane.showMessageDialog(this, "The password and confirm password are diferent");
        }
    }//GEN-LAST:event_changeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPasswordField actualPassword;
    private javax.swing.JButton change;
    private javax.swing.JPasswordField confirmNewPassword;
    private javax.swing.JLabel confirmNewPasswordLabel;
    private javax.swing.JButton goBaCk;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel imageBackground;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JLabel newPasswordLabel;
    private javax.swing.JLabel oldPasswordLabel;
    private javax.swing.JLabel title1Label;
    // End of variables declaration//GEN-END:variables
}
