package Vista;

import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import org.json.simple.*;
import org.json.simple.parser.ParseException;
import AppAccount.ContactManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.ParseException;

/**
 *
 * @author GROUP 1 UNC
 */
public class DeleteContactGUI extends javax.swing.JFrame {

    String username;

    /**
     * Creates new form DeleteContactGUI
     */
    public DeleteContactGUI(String username) throws ParseException {
        this.username = username;
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.changeContactList(this.listUserContacts());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1Label = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        title2Label = new javax.swing.JLabel();
        deleteContact = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        aboutLabel = new javax.swing.JLabel();
        imageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1Label.setFont(new java.awt.Font("AR DESTINE", 0, 48)); // NOI18N
        title1Label.setForeground(new java.awt.Color(255, 0, 0));
        title1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1Label.setText("DSDRisk Game");
        getContentPane().add(title1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 60));

        image1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Warriors.jpg"))); // NOI18N
        getContentPane().add(image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 220, 110));

        title2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2Label.setText("Choose contact to remove");
        getContentPane().add(title2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 182, 377, -1));

        deleteContact.setText("Delete contact");
        deleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteContactActionPerformed(evt);
            }
        });
        getContentPane().add(deleteContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        goBack.setText("Go back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 103, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Contact username"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 160, 90));

        aboutLabel.setForeground(new java.awt.Color(0, 0, 204));
        aboutLabel.setText("About this game");
        getContentPane().add(aboutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        imageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background.jpg"))); // NOI18N
        getContentPane().add(imageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteContactActionPerformed

        int row = jTable1.getSelectedRow();

        if (row >= 0) {

            try {
                JSONArray array = ContactManager.deleteContact(username, ((String) jTable1.getValueAt(row, 0)));
                String message = (String) (((JSONObject) (array.get(0))).get("message"));
                JOptionPane.showOptionDialog(null, message, "Message",
                        JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE,
                        null, new Object[]{"Accept"}, null);
                this.changeContactList(this.listUserContacts());

            } catch (ParseException ex) {
                Logger.getLogger(DeleteContactGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showOptionDialog(null, "Select a contact from the list", "Message",
                    JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE,
                    null, new Object[]{"Accept"}, null);
        }
    }//GEN-LAST:event_deleteContactActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed

    }//GEN-LAST:event_goBackActionPerformed

    private ArrayList<String> listUserContacts() throws ParseException {

        JSONArray array = ContactManager.listUserContacts(username);
        boolean status = (boolean) (((JSONObject) (array.get(0))).get("status"));
        ArrayList<String> contactsUsername = new ArrayList<>();

        if (status) {
            int contactsLength = ((JSONArray) (((JSONObject) (array.get(0))).get("contacts"))).size();
            for (int i = 0; i < contactsLength; i++) {
                contactsUsername.add(((String) ((JSONObject) (((JSONArray) (((JSONObject) (array.get(0))).get("contacts"))).get(i))).get("username")));
            }
        } else {
            String message = (String) (((JSONObject) (array.get(0))).get("message"));
            JOptionPane.showOptionDialog(null, message, "Message",
                    JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE,
                    null, new Object[]{"Accept"}, null);
        }
        return contactsUsername;
    }

    private void changeContactList(ArrayList<String> contactList) {

        Object[] columnNames = {"Conctact username"};
        Object[][] data = new Object[0][1];

        DefaultTableModel model = new DefaultTableModel(data, columnNames);

        Iterator<String> it = contactList.iterator();

        while (it.hasNext()) {
            Object newData[] = new Object[9];
            newData[0] = it.next();
            model.addRow(newData);
        }

        jTable1.setModel(model);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JButton deleteContact;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel imageBackground;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel title1Label;
    private javax.swing.JLabel title2Label;
    // End of variables declaration//GEN-END:variables

}
