package Vista;

import AppAccount.*;
import Controller.ConnectionStatus;
import Model.Account;
import Model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author GROUP 1 UNC
 */
public class LogInGUI extends javax.swing.JFrame {

    public User user;

    /**
     * Creates new form LogInGUI
     */
    public LogInGUI(User user) {
        initComponents();
        this.user = user;
        this.setVisible(true);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title1Label = new javax.swing.JLabel();
        title2Label = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        imageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Log in");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1Label.setFont(new java.awt.Font("AR DESTINE", 0, 48)); // NOI18N
        title1Label.setForeground(new java.awt.Color(255, 0, 0));
        title1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1Label.setText("DSDRisk Game");
        title1Label.setMinimumSize(new java.awt.Dimension(100, 55));
        title1Label.setPreferredSize(new java.awt.Dimension(50, 55));
        getContentPane().add(title1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 394, -1));

        title2Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        title2Label.setText("Enter username and password");
        getContentPane().add(title2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 70, -1, -1));

        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 119, -1, -1));

        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 160, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 116, 181, -1));

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        goBack.setText("Go back");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });
        getContentPane().add(goBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 157, 183, -1));

        imageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/background.jpg"))); // NOI18N
        getContentPane().add(imageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -6, 410, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //TODO complite login method
    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed

        ConnectionStatus status = AccountManager.loginAccount(username.getText(), String.valueOf(password.getPassword()));

        if (null != status) switch (status) {
            case SUCCESSFUL:
                User u = new User();
                u.status = "Online";
                /*ESTO NO DEBERIA IR, ¿COMO ES EL JSON QUE DEVUELVE PARA EL LOGN? */
                Account acc = new Account("dacanoc","123", "daca#gsf.com");                
                u.account=acc;
                /******************************************************************/
                new SessionGUI(u).setVisible(true);
                this.setVisible(false);
                break;
            case INVALID_PARAMETERS:
                JOptionPane.showMessageDialog(this, "The password and confirm password are diferent", "Message", JOptionPane.ERROR_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Username or password incorrect", "Message", JOptionPane.ERROR_MESSAGE);
                break;
        }

    }//GEN-LAST:event_enterActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        new DSDriskGame().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_goBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel imageBackground;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel title1Label;
    private javax.swing.JLabel title2Label;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
